# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_xbar_2/Audio_Interface_xbar_2.xci
# IP: The module: 'Audio_Interface_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_xbar_2/Audio_Interface_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_Interface_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_xbar_2/Audio_Interface_xbar_2.xci
# IP: The module: 'Audio_Interface_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_xbar_2/Audio_Interface_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_Interface_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
