# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/Audio_Interface_system_ila_0_0.xci
# IP: The module: 'Audio_Interface_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/bd_144b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b || ORIG_REF_NAME==bd_144b} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/bd_144b_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_ila_lib_0 || ORIG_REF_NAME==bd_144b_ila_lib_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_1/bd_144b_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_g_inst_0 || ORIG_REF_NAME==bd_144b_g_inst_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_2/bd_144b_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_aw_0 || ORIG_REF_NAME==bd_144b_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_3/bd_144b_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_w_0 || ORIG_REF_NAME==bd_144b_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_4/bd_144b_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_b_0 || ORIG_REF_NAME==bd_144b_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_5/bd_144b_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_ar_0 || ORIG_REF_NAME==bd_144b_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_6/bd_144b_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_r_0 || ORIG_REF_NAME==bd_144b_slot_0_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_7/bd_144b_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_aw_0 || ORIG_REF_NAME==bd_144b_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_8/bd_144b_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_w_0 || ORIG_REF_NAME==bd_144b_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_9/bd_144b_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_b_0 || ORIG_REF_NAME==bd_144b_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_10/bd_144b_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_ar_0 || ORIG_REF_NAME==bd_144b_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_11/bd_144b_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_r_0 || ORIG_REF_NAME==bd_144b_slot_1_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_12/bd_144b_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_aw_0 || ORIG_REF_NAME==bd_144b_slot_2_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_13/bd_144b_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_w_0 || ORIG_REF_NAME==bd_144b_slot_2_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_14/bd_144b_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_b_0 || ORIG_REF_NAME==bd_144b_slot_2_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_15/bd_144b_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_ar_0 || ORIG_REF_NAME==bd_144b_slot_2_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_16/bd_144b_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_r_0 || ORIG_REF_NAME==bd_144b_slot_2_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_17/bd_144b_slot_5_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_aw_0 || ORIG_REF_NAME==bd_144b_slot_5_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_18/bd_144b_slot_5_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_w_0 || ORIG_REF_NAME==bd_144b_slot_5_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_19/bd_144b_slot_5_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_b_0 || ORIG_REF_NAME==bd_144b_slot_5_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_20/bd_144b_slot_5_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_ar_0 || ORIG_REF_NAME==bd_144b_slot_5_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_21/bd_144b_slot_5_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_r_0 || ORIG_REF_NAME==bd_144b_slot_5_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_22/bd_144b_slot_6_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_aw_0 || ORIG_REF_NAME==bd_144b_slot_6_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_23/bd_144b_slot_6_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_w_0 || ORIG_REF_NAME==bd_144b_slot_6_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_24/bd_144b_slot_6_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_b_0 || ORIG_REF_NAME==bd_144b_slot_6_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_25/bd_144b_slot_6_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_ar_0 || ORIG_REF_NAME==bd_144b_slot_6_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_26/bd_144b_slot_6_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_r_0 || ORIG_REF_NAME==bd_144b_slot_6_r_0} -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/Audio_Interface_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_Interface_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_144b_ila_lib_0 || ORIG_REF_NAME==bd_144b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_144b_ila_lib_0 || ORIG_REF_NAME==bd_144b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/bd_144b_ila_lib_0_ooc.xdc

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/bd_144b_ooc.xdc

# IP: C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/Audio_Interface_system_ila_0_0.xci
# IP: The module: 'Audio_Interface_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/bd_144b.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b || ORIG_REF_NAME==bd_144b} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/bd_144b_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_ila_lib_0 || ORIG_REF_NAME==bd_144b_ila_lib_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_1/bd_144b_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_g_inst_0 || ORIG_REF_NAME==bd_144b_g_inst_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_2/bd_144b_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_aw_0 || ORIG_REF_NAME==bd_144b_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_3/bd_144b_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_w_0 || ORIG_REF_NAME==bd_144b_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_4/bd_144b_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_b_0 || ORIG_REF_NAME==bd_144b_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_5/bd_144b_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_ar_0 || ORIG_REF_NAME==bd_144b_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_6/bd_144b_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_0_r_0 || ORIG_REF_NAME==bd_144b_slot_0_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_7/bd_144b_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_aw_0 || ORIG_REF_NAME==bd_144b_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_8/bd_144b_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_w_0 || ORIG_REF_NAME==bd_144b_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_9/bd_144b_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_b_0 || ORIG_REF_NAME==bd_144b_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_10/bd_144b_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_ar_0 || ORIG_REF_NAME==bd_144b_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_11/bd_144b_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_1_r_0 || ORIG_REF_NAME==bd_144b_slot_1_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_12/bd_144b_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_aw_0 || ORIG_REF_NAME==bd_144b_slot_2_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_13/bd_144b_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_w_0 || ORIG_REF_NAME==bd_144b_slot_2_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_14/bd_144b_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_b_0 || ORIG_REF_NAME==bd_144b_slot_2_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_15/bd_144b_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_ar_0 || ORIG_REF_NAME==bd_144b_slot_2_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_16/bd_144b_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_2_r_0 || ORIG_REF_NAME==bd_144b_slot_2_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_17/bd_144b_slot_5_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_aw_0 || ORIG_REF_NAME==bd_144b_slot_5_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_18/bd_144b_slot_5_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_w_0 || ORIG_REF_NAME==bd_144b_slot_5_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_19/bd_144b_slot_5_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_b_0 || ORIG_REF_NAME==bd_144b_slot_5_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_20/bd_144b_slot_5_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_ar_0 || ORIG_REF_NAME==bd_144b_slot_5_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_21/bd_144b_slot_5_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_5_r_0 || ORIG_REF_NAME==bd_144b_slot_5_r_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_22/bd_144b_slot_6_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_aw_0 || ORIG_REF_NAME==bd_144b_slot_6_aw_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_23/bd_144b_slot_6_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_w_0 || ORIG_REF_NAME==bd_144b_slot_6_w_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_24/bd_144b_slot_6_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_b_0 || ORIG_REF_NAME==bd_144b_slot_6_b_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_25/bd_144b_slot_6_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_ar_0 || ORIG_REF_NAME==bd_144b_slot_6_ar_0} -quiet] -quiet

# IP: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_26/bd_144b_slot_6_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_144b_slot_6_r_0 || ORIG_REF_NAME==bd_144b_slot_6_r_0} -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/Audio_Interface_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_Interface_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_144b_ila_lib_0 || ORIG_REF_NAME==bd_144b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_144b_ila_lib_0 || ORIG_REF_NAME==bd_144b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/bd_144b_ila_lib_0_ooc.xdc

# XDC: c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/bd_144b_ooc.xdc
