# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {1}  -id {BD 41-1599}  -string {{ERROR: [BD 41-1599] /processing_system7_0/S_AXI_GP0/GP0_M_AXI_GP0 is already excluded.}}  -suppress 
set_msg_config  -ruleid {11}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {12}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {2}  -id {BD 5-294}  -string {{ERROR: [BD 5-294] Error excluding segment}}  -suppress 
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.cache/wt [current_project]
set_property parent.project_path C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/panze/Documents/Project/Vivado_Work/ip_repo [current_project]
set_property ip_output_repo c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/hdl/Audio_Interface_wrapper.vhd
add_files C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/Audio_Interface.bd
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_processing_system7_0_3/Audio_Interface_processing_system7_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_rst_ps7_0_100M_0/Audio_Interface_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_rst_ps7_0_100M_0/Audio_Interface_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_rst_ps7_0_100M_0/Audio_Interface_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_xbar_2/Audio_Interface_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_gpio_0_0/Audio_Interface_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_gpio_0_0/Audio_Interface_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_gpio_0_0/Audio_Interface_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_fifo_generator_0_0/Audio_Interface_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_fifo_generator_0_0/Audio_Interface_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_10/bd_9b15_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_16/bd_9b15_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_20/bd_9b15_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_21/bd_9b15_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_22/bd_9b15_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_23/bd_9b15_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_24/bd_9b15_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_25/bd_9b15_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_17/bd_9b15_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_18/bd_9b15_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_19/bd_9b15_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_11/bd_9b15_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_12/bd_9b15_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_2/bd_9b15_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_3/bd_9b15_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_4/bd_9b15_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_5/bd_9b15_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_6/bd_9b15_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_1/bd_9b15_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/bd_0/ip/ip_1/bd_9b15_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_xfft_0_0/Audio_Interface_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_dma_0_1/Audio_Interface_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_dma_0_1/Audio_Interface_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_axi_dma_0_1/Audio_Interface_axi_dma_0_1_clocks.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/ip/ip_0/bd_144b_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/bd_0/bd_144b_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/Audio_Interface_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_fifo_generator_1_0/Audio_Interface_fifo_generator_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_fifo_generator_1_0/Audio_Interface_fifo_generator_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/ip/Audio_Interface_auto_pc_0/Audio_Interface_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/sources_1/bd/Audio_Interface/Audio_Interface_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/constrs_1/new/base.xdc
set_property used_in_implementation false [get_files C:/Users/panze/Documents/Project/Vivado_Work/Spectral_Analyzer/Spectral_Analyzer.srcs/constrs_1/new/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Audio_Interface_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Audio_Interface_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Audio_Interface_wrapper_utilization_synth.rpt -pb Audio_Interface_wrapper_utilization_synth.pb"
