# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/base.xdc

# Block Designs: bd/Audio_Interface/Audio_Interface.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface || ORIG_REF_NAME==Audio_Interface} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_processing_system7_0_3/Audio_Interface_processing_system7_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_processing_system7_0_3 || ORIG_REF_NAME==Audio_Interface_processing_system7_0_3} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_ps7_0_axi_periph_1/Audio_Interface_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_ps7_0_axi_periph_1 || ORIG_REF_NAME==Audio_Interface_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_rst_ps7_0_100M_0/Audio_Interface_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_rst_ps7_0_100M_0 || ORIG_REF_NAME==Audio_Interface_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_xbar_2/Audio_Interface_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_xbar_2 || ORIG_REF_NAME==Audio_Interface_xbar_2} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_axi_gpio_0_0/Audio_Interface_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_axi_gpio_0_0 || ORIG_REF_NAME==Audio_Interface_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_zed_audio_ctrl_0_0/Audio_Interface_zed_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_zed_audio_ctrl_0_0 || ORIG_REF_NAME==Audio_Interface_zed_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_fifo_generator_0_0/Audio_Interface_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_fifo_generator_0_0 || ORIG_REF_NAME==Audio_Interface_fifo_generator_0_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_axi_smc_0/Audio_Interface_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_axi_smc_0 || ORIG_REF_NAME==Audio_Interface_axi_smc_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_xfft_0_0/Audio_Interface_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_xfft_0_0 || ORIG_REF_NAME==Audio_Interface_xfft_0_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_xlconstant_0_0/Audio_Interface_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_xlconstant_0_0 || ORIG_REF_NAME==Audio_Interface_xlconstant_0_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_xlconstant_1_0/Audio_Interface_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_xlconstant_1_0 || ORIG_REF_NAME==Audio_Interface_xlconstant_1_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_axi_dma_0_1/Audio_Interface_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_axi_dma_0_1 || ORIG_REF_NAME==Audio_Interface_axi_dma_0_1} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_system_ila_0_0/Audio_Interface_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_system_ila_0_0 || ORIG_REF_NAME==Audio_Interface_system_ila_0_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_fifo_generator_1_0/Audio_Interface_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_fifo_generator_1_0 || ORIG_REF_NAME==Audio_Interface_fifo_generator_1_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_xlconstant_2_0/Audio_Interface_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_xlconstant_2_0 || ORIG_REF_NAME==Audio_Interface_xlconstant_2_0} -quiet] -quiet

# IP: bd/Audio_Interface/ip/Audio_Interface_auto_pc_0/Audio_Interface_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Audio_Interface_auto_pc_0 || ORIG_REF_NAME==Audio_Interface_auto_pc_0} -quiet] -quiet

# XDC: bd/Audio_Interface/Audio_Interface_ooc.xdc
